language: python
python:
  - "3.4"
cache: pip
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install nose
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE mydiary_db;" -U postgres
script:
  - nosetests -v --with-coverage --cover-package=mydiary
after_success:
  - coveralls