language: python
python:
  - "3.4"
cache: pip
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install nose
script:
  - nosetests --with-coverage
after_success:
  - coveralls