language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install nose
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE mydiarydb;" -U postgres
  - psql -c "CREATE DATABASE testdb;" -U postgres
script:
  - nosetests -v --with-coverage --cover-package=mydiary
after_success:
  - coveralls